server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/am_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: Xz112500
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-wait: 60000
      initial-size: 30
      min-idle: 10
      max-active: 1500
      timeBetweenEvictionRunsMillis: 2000
      minEvictableIdleTimeMillis: 30000
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pojo
